# Generated by Django 5.0.1 on 2026-02-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('indic_code', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('source_text_hash', models.CharField(db_index=True, max_length=64)),
                ('source_language', models.CharField(default='en', max_length=10)),
                ('target_language', models.CharField(db_index=True, max_length=10)),
                ('translated_text', models.TextField()),
                ('translation_service', models.CharField(default='indictrans2', max_length=50)),
                ('content_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source_text_hash', 'target_language'], name='translation_source__159e2b_idx'), models.Index(fields=['content_type', 'target_language'], name='translation_content_895a8d_idx')],
                'unique_together': {('source_text_hash', 'source_language', 'target_language')},
            },
        ),
    ]
