// @ts-nocheck 
// Game Development with Unity and C# course content 
import { moduleDetails } from './module-details'; 
import { phase1DetailedContent } from './phase-01-detailed'; 
 
const modules = [ 
  [1, 'Beginner', 'Unity Workspace Setup and Editor Navigation', 1, 'Set up workspace, scenes, prefabs, and clean structure.'], 
  [1, 'Beginner', 'C# Basics for Unity Scripts', 2, 'MonoBehaviour lifecycle, input, and readable script design.'], 
  [1, 'Beginner', 'Components and GameObject Composition', 3, 'Use composition with focused, testable components.'], 
  [1, 'Beginner', 'Input and Player Movement Foundations', 4, 'Implement responsive movement and tune control feel.'], 
  [1, 'Beginner', '2D Physics and Collision Systems', 5, 'Build collision-driven gameplay with stable physics.'], 
  [2, 'Intermediate', 'Spawning and Game State Flow', 6, 'Create wave spawning and explicit game state transitions.'], 
  [2, 'Intermediate', 'Data-Driven Design with ScriptableObjects', 7, 'Move balancing from code into data assets.'], 
  [2, 'Intermediate', 'Animation Controllers and State Flow', 8, 'Sync animation states with gameplay logic.'], 
  [2, 'Intermediate', 'AI Behaviors I: Patrol Chase Attack', 9, 'Implement enemy state machines with fallback logic.'], 
  [2, 'Intermediate', 'AI Behaviors II: Variants and Encounters', 10, 'Build enemy archetypes and readable encounters.'], 
  [3, 'Advanced', 'Combat Damage and Weapons', 11, 'Implement deterministic damage and weapon systems.'], 
  [3, 'Advanced', 'Scene Management and Loading', 12, 'Use bootstrap and async scene transitions safely.'], 
  [3, 'Advanced', 'Menu UI Architecture and Settings', 13, 'Create complete menu flow with persistent settings.'], 
  [3, 'Advanced', 'VFX and Game Feel Polish', 14, 'Improve readability and feedback using effects.'], 
  [3, 'Advanced', 'Performance Profiling and Optimization', 15, 'Optimize based on profiler evidence and metrics.'], 
  [4, 'Production', 'Build Pipeline and Release QA', 16, 'Create reproducible builds and QA checklist.'], 
  [4, 'Production', 'Production Sprint Delivery', 17, 'Ship one major feature and one polish feature.'], 
  [4, 'Production', 'Level Design Progression', 18, 'Build 3 levels with clear difficulty progression.'], 
  [4, 'Production', 'Objectives and Event Systems', 19, 'Track mission objectives using event-driven updates.'], 
  [4, 'Production', 'Capstone Integration and Portfolio Delivery', 20, 'Integrate all systems and ship capstone build.'], 
  [5, 'Beginner Projects', 'Roll-a-Ball', 21, 'Build a 3D collection game using Rigidbody movement and pickups.'], 
  [5, 'Beginner Projects', 'Pong', 22, 'Create a 2D arcade game with paddle control, physics, and scoring.'], 
  [5, 'Beginner Projects', 'Space Shooter', 23, 'Build a 2D shooter with prefabs, spawning, and game over flow.'], 
  [5, 'Beginner Projects', 'Snake', 24, 'Create a grid-based snake game with growth and fail states.'], 
  [5, 'Beginner Projects', 'Endless Runner', 25, 'Develop a runner with jump timing, obstacle spawning, and score loop.'] 
]; 
 
const phaseTitles: Record<number, string> = { 
  1: 'Phase 1: Beginner Foundations', 
  2: 'Phase 2: Intermediate Gameplay Systems', 
  3: 'Phase 3: Advanced Engineering', 
  4: 'Phase 4: Production and Capstone', 
  5: 'Phase 5: Five Games from Scratch' 
};
 
function buildLesson(row: any[], index: number) { 
  const phaseId = row[0]; 
  const stage = row[1]; 
  const moduleTitle = row[2]; 
  const chapter = row[3]; 
  const focus = row[4]; 
  const moduleNumber = index + 1; 
 
  const details = moduleDetails[moduleNumber] ? moduleDetails[moduleNumber] : { 
    learningObjectives: ['Build production-ready gameplay for this chapter'], 
    whyMatters: [focus], 
    workflow: ['Study chapter code', 'Implement extension', 'Test and validate'], 
    validation: ['No console errors', 'Feature works as expected'], 
    exercises: ['Complete chapter exercises'] 
  }; 
 
  const phase1 = (phase1DetailedContent as any)[moduleNumber]; 
  const deepExplanation = phase1 ? phase1.deepExplanation : ['Read chapter baseline, implement extension, and validate behavior.']; 
  const pitfalls = phase1 ? phase1.pitfalls : ['Avoid hidden dependencies and hardcoded values.']; 
  const deliverables = phase1 ? phase1.deliverables : ['Runnable module with test evidence.']; 
  const rubric = phase1 ? phase1.rubric : ['Correctness, code quality, validation, production readiness.']; 
  const guidedLab = phase1 ? phase1.guidedLab : ['Step 1: Baseline', 'Step 2: Extension', 'Step 3: Test']; 
  const checkpoints = phase1 ? phase1.checkpoints : ['Checkpoint: baseline and extension validated']; 
  const assessment = phase1 ? phase1.assessment : ['Explain design decisions and demonstrate output']; 
  const expectedOutput = phase1 ? phase1.expectedOutput : ['Stable runnable module output']; 
  const note = '### Compiler Note\nNote: This in-browser compiler uses a lightweight C# sandbox and does not include full UnityEngine/runtime support. If a Unity-specific script fails here, run it inside Unity Editor (recommended) to validate actual behavior.'; 

  const formatStructuredNumberedBlock = (lines: string[]) => {
    const grouped: string[] = [];
    let current = '';

    for (const line of lines) {
      if (/^\d+\./.test(line)) {
        if (current) grouped.push(current);
        current = line;
      } else if (/^Step\s+\d+:/i.test(line)) {
        if (current) grouped.push(current);
        current = line;
      } else {
        current = current ? current + '<br/>' + line : line;
      }
    }

    if (current) grouped.push(current);
    return grouped.join('\n\n');
  };
 
  return { 
    phaseId: phaseId, 
    title: 'Module ' + moduleNumber + ': ' + moduleTitle, 
    description: [ 
      '## Module ' + moduleNumber + ': ' + moduleTitle, 
      '', 
       
       
       
       
      '', 
      '### Learning Objectives', 
      details.learningObjectives.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Deep Explanation', 
      (moduleNumber === 1 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 2 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 3 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 4 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 5 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 6 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 7 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 8 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 9 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 10 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 11 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 12 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 13 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 14 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 15 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 16 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 17 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 18 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 19 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 20 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 21 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 22 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 23 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 24 ? formatStructuredNumberedBlock(deepExplanation) : moduleNumber === 25 ? formatStructuredNumberedBlock(deepExplanation) : deepExplanation.map(function(x) { return '- ' + x; }).join('\n')), 
      '', 
      '### Why This Matters', 
      details.whyMatters.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Implementation Workflow', 
      details.workflow.map(function(x, i) { return (i + 1) + '. ' + x; }).join('\n'),
      '', 
      '### Common Pitfalls and How to Avoid Them', 
      pitfalls.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Validation Checklist', 
      details.validation.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Chapter Exercise Pack', 
      details.exercises.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Guided Lab (Step-by-Step)', 
      (moduleNumber === 1 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 2 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 3 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 4 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 5 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 6 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 7 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 8 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 9 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 10 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 11 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 12 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 13 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 14 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 15 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 16 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 17 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 18 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 19 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 20 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 21 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 22 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 23 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 24 ? formatStructuredNumberedBlock(guidedLab) : moduleNumber === 25 ? formatStructuredNumberedBlock(guidedLab) : guidedLab.map(function(x, i) { return (i + 1) + '. ' + x; }).join('\n')), 
      '', 
      '### Progress Checkpoints', 
      checkpoints.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Assessment Tasks', 
      assessment.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Expected Output', 
      expectedOutput.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Deliverables', 
      deliverables.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Assessment Rubric', 
      rubric.map(function(x) { return '- ' + x; }).join('\n'), 
      '', 
      '### Milestone', 
      'Deliver a runnable module implementation with chapter evidence and documentation.', 
      '', 
      note 
    ].join('\n'), 
    code: moduleNumber === 2 ? [ 
      'using UnityEngine;', 
      '', 
      'public class PlayerController : MonoBehaviour', 
      '{', 
      '    [Header("Movement Settings")]', 
      '    [Tooltip("Horizontal movement speed in units per second.")]', 
      '    [SerializeField] private float moveSpeed = 10f;', 
      '    [SerializeField] private float jumpForce = 5f;', 
      '', 
      '    private float horizontalInput;', 
      '    private bool jumpRequested = false;', 
      '    private Rigidbody2D rb;', 
      '', 
      '    private void Awake()', 
      '    {', 
      '        rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D;', 
      '        if (rb == null) Debug.LogError("PlayerController: Missing Rigidbody2D!");', 
      '    }', 
      '', 
      '    private void Update()', 
      '    {', 
      '        horizontalInput = Input.GetAxisRaw("Horizontal");', 
      '        if (Input.GetButtonDown("Jump"))', 
      '        {', 
      '            jumpRequested = true;', 
      '        }', 
      '    }', 
      '', 
      '    private void FixedUpdate()', 
      '    {', 
      '        ApplyMovement();', 
      '        if (jumpRequested)', 
      '        {', 
      '            ApplyJump();', 
      '            jumpRequested = false;', 
      '        }', 
      '    }', 
      '', 
      '    private void ApplyMovement()', 
      '    {', 
      '        rb.velocity = new Vector2(horizontalInput * moveSpeed, rb.velocity.y);', 
      '    }', 
      '', 
      '    private void ApplyJump()', 
      '    {', 
      '        rb.AddForce(Vector2.up * jumpForce, ForceMode2D.Impulse);', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 3 ? [ 
      'using UnityEngine;', 
      '', 
      '[RequireComponent(typeof(Collider2D))]', 
      'public class Health : MonoBehaviour', 
      '{', 
      '    [Header("Stats")]', 
      '    [SerializeField] private float maxHealth = 100f;', 
      '    private float currentHealth;', 
      '', 
      '    [Header("Feedback")]', 
      '    [SerializeField] private ParticleSystem hitEffect;', 
      '', 
      '    private void Awake()', 
      '    {', 
      '        currentHealth = maxHealth;', 
      '    }', 
      '', 
      '    public void TakeDamage(float amount)', 
      '    {', 
      '        currentHealth -= amount;', 
      '        Debug.Log($"{gameObject.name} took {amount} damage. HP: {currentHealth}");', 
      '', 
      '        if (hitEffect != null)', 
      '        {', 
      '            hitEffect.Play();', 
      '        }', 
      '', 
      '    }', 
      '', 
      '    private void Die()', 
      '    {', 
      '        Debug.Log($"{gameObject.name} has been destroyed!");', 
      '        Destroy(gameObject);', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 4 ? [
      'using UnityEngine;',
      '', 
      '[RequireComponent(typeof(Rigidbody2D))]', 
      'public class PlayerMotor : MonoBehaviour', 
      '{', 
      '    [Header("Movement Stats")]', 
      '    [SerializeField] private float acceleration = 50f;', 
      '    [SerializeField] private float maxSpeed = 10f;', 
      '    [SerializeField] private float linearDrag = 4f;', 
      '', 
      '    [Header("Jump Stats")]', 
      '    [SerializeField] private float jumpForce = 12f;', 
      '    [SerializeField] private LayerMask groundLayer;', 
      '    [SerializeField] private Transform groundCheck;', 
      '', 
      '    private Rigidbody2D rb;',
      '    private float horizontalInput;', 
      '    private bool isGrounded;', 
      '', 
      '    private void Awake()', 
      '    {', 
      '        rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D;', 
      '        if (rb == null) Debug.LogError("PlayerMotor: Missing Rigidbody2D!");', 
      '        rb.drag = linearDrag;', 
      '    }', 
      '', 
      '    private void Update()', 
      '    {', 
      '        horizontalInput = Input.GetAxisRaw("Horizontal");', 
      '        isGrounded = Physics2D.OverlapCircle(groundCheck.position, 0.2f, groundLayer);',
      '        if (Input.GetButtonDown("Jump") && isGrounded)', 
      '        {', 
      '            ApplyJump();', 
      '        }', 
      '    }', 
      '', 
      '    private void FixedUpdate()', 
      '    {', 
      '        ApplyMovement();', 
      '    }', 
      '', 
      '    private void ApplyMovement()', 
      '    {', 
      '        rb.AddForce(new Vector2(horizontalInput * acceleration, 0));',
      '        if (Mathf.Abs(rb.velocity.x) > maxSpeed)', 
      '        {', 
      '            rb.velocity = new Vector2(Mathf.Sign(rb.velocity.x) * maxSpeed, rb.velocity.y);', 
      '        }', 
      '    }', 
      '', 
      '    private void ApplyJump()', 
      '    {', 
      '        rb.velocity = new Vector2(rb.velocity.x, 0);', 
      '        rb.AddForce(Vector2.up * jumpForce, ForceMode2D.Impulse);', 
      '    }', 
      '}', 
    ].join('\n') : moduleNumber === 5 ? [ 
      'using UnityEngine;', 
      '', 
      'public class HazardHandler : MonoBehaviour', 
      '{', 
      '    [Header("Respawn Settings")]', 
      '    [SerializeField] private Vector3 currentCheckpoint;', 
      '    [SerializeField] private float damageKnockback = 5f;', 
      '', 
      '    private Rigidbody2D rb;', 
      '', 
      '    private void Awake()', 
      '    {', 
      '        rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D;', 
      '        currentCheckpoint = transform.position;', 
      '    }', 
      '', 
      '    private void OnCollisionEnter2D(Collision2D collision)', 
      '    {', 
      '        if (collision.gameObject.CompareTag("Hazard"))', 
      '        {', 
      '            ApplyKnockback(collision.contacts[0].normal);', 
      '            Respawn();', 
      '        }', 
      '    }', 
      '', 
      '    private void OnTriggerEnter2D(Collider2D other)', 
      '    {', 
      '        if (other.CompareTag("Checkpoint"))', 
      '        {', 
      '            currentCheckpoint = other.transform.position;', 
      '            Debug.Log("Checkpoint Saved!");', 
      '        }', 
      '        else if (other.CompareTag("DeathZone"))', 
      '        {', 
      '            Respawn();', 
      '        }', 
      '    }', 
      '', 
      '    private void ApplyKnockback(Vector2 hitNormal)', 
      '    {', 
      '        rb.velocity = Vector2.zero;', 
      '        rb.AddForce(hitNormal * damageKnockback, ForceMode2D.Impulse);', 
      '    }', 
      '', 
      '    private void Respawn()', 
      '    {', 
      '        Debug.Log("Player Died! Respawning...");', 
      '        transform.position = currentCheckpoint;', 
      '        rb.velocity = Vector2.zero;', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 6 ? [
      'using UnityEngine;',
      'using System.Collections; // Required for Coroutines',
      '',
      'public class WaveManager : MonoBehaviour',
      '{',
      '    public enum GameState { Waiting, Playing, GameOver }',
      '    public GameState currentState = GameState.Waiting;',
      '',
      '    [Header("Spawner Settings")]',
      '    [SerializeField] private GameObject enemyPrefab;',
      '    [SerializeField] private Transform[] spawnPoints;',
      '    [SerializeField] private float timeBetweenSpawns = 2f;',
      '',
      '    public static WaveManager Instance;',
      '',
      '    private void Awake()',
      '    {',
      '        if (Instance == null) Instance = this;',
      '        else Destroy(gameObject);',
      '    }',
      '',
      '    private void Start()',
      '    {',
      '        StartGame();',
      '    }',
      '',
      '    public void StartGame()',
      '    {',
      '        currentState = GameState.Playing;',
      '        StartCoroutine(SpawnWaveRoutine());',
      '    }',
      '',
      '    private IEnumerator SpawnWaveRoutine()',
      '    {',
      '        while (currentState == GameState.Playing)',
      '        {',
      '            SpawnEnemy();',
      '            yield return new WaitForSeconds(timeBetweenSpawns);',
      '        }',
      '    }',
      '',
      '    private void SpawnEnemy()',
      '    {',
      '        int randomIndex = Random.Range(0, spawnPoints.Length);',
      '        Instantiate(enemyPrefab, spawnPoints[randomIndex].position, Quaternion.identity);',
      '        Debug.Log("Enemy Spawned!");',
      '    }',
      '',
      '    public void EndGame()',
      '    {',
      '        currentState = GameState.GameOver;',
      '        Debug.Log("Game Over! Stopping Spawner.");',
      '    }',
      '}'
    ].join('\n') : moduleNumber === 7 ? [
      'using UnityEngine;',
      '',
      '[CreateAssetMenu(fileName = "NewEnemyConfig", menuName = "GameData/EnemyConfig")]',
      'public class EnemyConfig : ScriptableObject',
      '{',
      '    public string enemyName;',
      '    public float maxHealth;',
      '    public float moveSpeed;',
      '    public Color displayColor;',
      '    public GameObject deathEffectPrefab;',
      '}',
      '',
      'public class EnemyController : MonoBehaviour',
      '{',
      '    [SerializeField] private EnemyConfig data;',
      '    private float currentHealth;',
      '    private SpriteRenderer sRenderer;',
      '',
      '    private void Awake()',
      '    {',
      '        sRenderer = GetComponent(typeof(SpriteRenderer)) as SpriteRenderer;',
      '        if (data == null)',
      '        {',
      '            Debug.LogError("Enemy is missing its Config Data!");',
      '            return;',
      '        }',
      '        currentHealth = data.maxHealth;',
      '        if (sRenderer != null) sRenderer.color = data.displayColor;',
      '        Debug.Log("Initialized " + data.enemyName + " with " + currentHealth + " HP.");',
      '    }',
      '',
      '    public void Move()',
      '    {',
      '        transform.Translate(Vector3.left * data.moveSpeed * Time.deltaTime);',
      '    }',
      '}'
    ].join('\n') : moduleNumber === 8 ? [ 
      'using UnityEngine;', 
      '', 
      'public class PlayerAnimation : MonoBehaviour', 
      '{', 
      '    private Animator anim;', 
      '    private Rigidbody2D rb;', 
      '    private SpriteRenderer spriteRenderer;', 
      '', 
      '    private void Awake()', 
      '    {', 
      '        anim = GetComponent(typeof(Animator)) as Animator;', 
      '        rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D;', 
      '        spriteRenderer = GetComponent(typeof(SpriteRenderer)) as SpriteRenderer;', 
      '    }', 
      '', 
      '    private void Update()', 
      '    {', 
      '        float speed = Mathf.Abs(rb.velocity.x);', 
      '        anim.SetFloat("speed", speed);', 
      '        if (rb.velocity.x > 0.1f) spriteRenderer.flipX = false;', 
      '        else if (rb.velocity.x < -0.1f) spriteRenderer.flipX = true;', 
      '        bool grounded = Mathf.Abs(rb.velocity.y) < 0.01f;', 
      '        anim.SetBool("isGrounded", grounded);', 
      '    }', 
      '', 
      '    public void OnAttackHitFrame()', 
      '    {', 
      '        Debug.Log("Animation Event Triggered: Dealing Damage!");', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 9 ? [ 
      'using UnityEngine;', 
      'public class EnemyBrain : MonoBehaviour', 
      '{', 
      '    public enum AIState { Patrolling, Chasing, Attacking }', 
      '    [SerializeField] private AIState currentState = AIState.Patrolling;', 
      '    [SerializeField] private float detectionRange = 5f;', 
      '    [SerializeField] private float attackRange = 1.5f;', 
      '    [SerializeField] private Transform playerTransform;', 
      '    [SerializeField] private float moveSpeed = 2f;', 
      '    [SerializeField] private Transform[] patrolPoints;', 
      '    private int currentPointIndex = 0;', 
      '    private void Update(){ if (playerTransform == null) return; float d = Vector3.Distance(transform.position, playerTransform.position); if (d < attackRange) currentState = AIState.Attacking; else if (d < detectionRange) currentState = AIState.Chasing; else currentState = AIState.Patrolling; switch (currentState){ case AIState.Patrolling: DoPatrol(); break; case AIState.Chasing: DoChase(); break; case AIState.Attacking: DoAttack(); break; } }', 
      '    private void DoPatrol(){ if (patrolPoints == null) return; if (patrolPoints.Length == 0) return; Transform t = patrolPoints[currentPointIndex]; MoveTowards(t.position); if (Vector3.Distance(transform.position, t.position) < 0.2f) currentPointIndex = (currentPointIndex + 1) % patrolPoints.Length; }', 
      '    private void DoChase(){ MoveTowards(playerTransform.position); }', 
      '    private void DoAttack(){ Debug.Log("Enemy is Attacking!"); }', 
      '    private void MoveTowards(Vector3 target){ transform.position = Vector3.MoveTowards(transform.position, target, moveSpeed * Time.deltaTime); }', 
      '    private void OnDrawGizmosSelected(){ Gizmos.color = Color.yellow; Gizmos.DrawWireSphere(transform.position, detectionRange); Gizmos.color = Color.red; Gizmos.DrawWireSphere(transform.position, attackRange); }', 
      '}' 
    ].join('\n') : moduleNumber === 10 ? [ 
      'using UnityEngine;', 
      'using System.Collections;', 
      'public class EnemyVariantBrain : MonoBehaviour', 
      '{', 
      '    [SerializeField] private EnemyConfig config;', 
      '    [SerializeField] private SpriteRenderer sRenderer;', 
      '    [SerializeField] private float attackCooldown = 1f;', 
      '    private bool isAttacking = false;', 
      '    public void StartAttackSequence(GameObject target){ if (isAttacking) return; StartCoroutine(AttackRoutine(target)); }', 
      '    private IEnumerator AttackRoutine(GameObject target){ isAttacking = true; Color originalColor = sRenderer != null ? sRenderer.color : Color.white; if (sRenderer != null) sRenderer.color = Color.red; yield return new WaitForSeconds(0.5f); if (target != null){ Debug.Log("HIT! " + (config != null ? config.enemyName : "Enemy") + " dealt damage."); } if (sRenderer != null) sRenderer.color = originalColor; yield return new WaitForSeconds(attackCooldown); isAttacking = false; }', 
      '}' 
    ].join('\n') : moduleNumber === 11 ? [ 
      'using UnityEngine;', 
      'public interface IDamageable { void TakeDamage(float amount, Vector2 hitDirection); }', 
      'public class RaycastWeapon : MonoBehaviour', 
      '{', 
      '    [SerializeField] private float damage = 20f;', 
      '    [SerializeField] private float fireRate = 0.5f;', 
      '    [SerializeField] private LayerMask hitLayers;', 
      '    private float nextFireTime;', 
      '    private void Update(){ Shoot(); }', 
      '    private void Shoot(){ RaycastHit2D hit = Physics2D.Raycast(transform.position, transform.right, 10f, hitLayers); if (hit.collider != null){ Debug.Log("Hit " + hit.collider.name + "!"); } }', 
      '}' 
    ].join('\n') : moduleNumber === 12 ? [ 
      'using UnityEngine;', 
      'using UnityEngine.SceneManagement;', 
      'using System.Collections;', 
      'public class SceneLoader : MonoBehaviour', 
      '{', 
      '    public static SceneLoader Instance;', 
      '    [SerializeField] private GameObject loadingScreen;', 
      '    [SerializeField] private UnityEngine.UI.Slider progressBar;', 
      '    private void Awake(){ if (Instance == null){ Instance = this; DontDestroyOnLoad(gameObject);} else { Destroy(gameObject);} }', 
      '    public void LoadLevel(string sceneName){ StartCoroutine(LoadAsynchronously(sceneName)); }', 
      '    private IEnumerator LoadAsynchronously(string sceneName){ if (loadingScreen != null) loadingScreen.SetActive(true); AsyncOperation operation = SceneManager.LoadSceneAsync(sceneName); while (!operation.isDone){ float progress = Mathf.Clamp01(operation.progress / 0.9f); if (progressBar != null) progressBar.value = progress; yield return null; } if (loadingScreen != null) loadingScreen.SetActive(false); }', 
      '}' 
    ].join('\n') : moduleNumber === 13 ? [ 
      'using UnityEngine;', 
      'public class MenuController : MonoBehaviour', 
      '{', 
      '    [SerializeField] private GameObject pauseMenuUI;', 
      '    private bool isPaused = false;', 
      '    private void Update(){ if (Input.GetKeyDown(KeyCode.Escape)){ if (isPaused) Resume(); else Pause(); } }', 
      '    public void Pause(){ if (pauseMenuUI != null) pauseMenuUI.SetActive(true); Time.timeScale = 0f; isPaused = true; }', 
      '    public void Resume(){ if (pauseMenuUI != null) pauseMenuUI.SetActive(false); Time.timeScale = 1f; isPaused = false; }', 
      '    public void SetVolume(float volume){ PlayerPrefs.SetFloat("MasterVolume", volume); }', 
      '}' 
    ].join('\n') : moduleNumber === 14 ? [ 
      'using UnityEngine;', 
      'using System.Collections;', 
      'public class GameJuice : MonoBehaviour', 
      '{', 
      '    public static GameJuice Instance;', 
      '    private void Awake(){ Instance = this; }', 
      '    public void HitStop(float duration){ StartCoroutine(HitStopRoutine(duration)); }', 
      '    private IEnumerator HitStopRoutine(float duration){ Time.timeScale = 0f; yield return new WaitForSecondsRealtime(duration); Time.timeScale = 1f; }', 
      '    public void ShakeCamera(float duration, float magnitude){ StartCoroutine(ShakeRoutine(duration, magnitude)); }', 
      '    private IEnumerator ShakeRoutine(float duration, float magnitude){', 
      '        if (Camera.main == null) yield break;', 
      '        Vector3 originalPos = Camera.main.transform.localPosition;', 
      '        for (int frame = 0; frame != 12; frame++){', 
      '            float x = Random.Range(-1f, 1f) * magnitude;', 
      '            float y = Random.Range(-1f, 1f) * magnitude;', 
      '            Camera.main.transform.localPosition = new Vector3(x, y, originalPos.z);', 
      '            yield return null;', 
      '        }', 
      '        Camera.main.transform.localPosition = originalPos;', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 15 ? [
      'using UnityEngine;',
      'using System.Collections.Generic;',
      'public class SimpleObjectPool : MonoBehaviour',
      '{',
      '    public static SimpleObjectPool Instance;',
      '    [SerializeField] private GameObject prefabToPool;',
      '    [SerializeField] private int poolSize = 20;',
      '    private GameObject[] pool;',
      '    private void Awake(){',
      '        Instance = this;',
      '        pool = new GameObject[poolSize];',
      '        int i = 0;',
      '        while (i != poolSize){',
      '            GameObject obj = Instantiate(prefabToPool);',
      '            obj.SetActive(false);',
      '            pool[i] = obj;',
      '            i = i + 1;',
      '        }',
      '    }',
      '    public GameObject GetPooledObject(){',
      '        int i = 0;',
      '        while (i != poolSize){',
      '            if (!pool[i].activeInHierarchy){',
      '                return pool[i];',
      '            }',
      '            i = i + 1;',
      '        }',
      '        return null;',
      '    }',
      '}'
    ].join('\n') : moduleNumber === 16 ? [ 
      'using UnityEngine;', 
      'using TMPro;', 
      'public class BuildInfoDisplay : MonoBehaviour', 
      '{', 
      '    [SerializeField] private TextMeshProUGUI versionText;', 
      '    private void Start()', 
      '    {', 
      '        string currentVersion = Application.version;', 
      '        string platform = Application.platform.ToString();', 
      '        string buildType = Debug.isDebugBuild ? "DEVELOPMENT" : "RELEASE";', 
      '        if (versionText != null)', 
      '        {', 
      '            versionText.text = "v" + currentVersion + " | " + platform + " | " + buildType;', 
      '        }', 
      '        Debug.Log("Build Initialized: v" + currentVersion + " on " + platform);', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 17 ? [ 
      'using UnityEngine;', 
      'public class SprintFeatureManager : MonoBehaviour', 
      '{', 
      '    [Header("Sprint 17: Experimental Features")]', 
      '    [Tooltip("Enable this to test the new Boss AI behavior.")]', 
      '    [SerializeField] private bool enableNewBossAI = false;', 
      '    [SerializeField] private GameObject oldBossLogic;', 
      '    [SerializeField] private GameObject experimentalBossLogic;', 
      '    private void Start()', 
      '    {', 
      '        if (enableNewBossAI)', 
      '        {', 
      '            if (experimentalBossLogic != null) experimentalBossLogic.SetActive(true);', 
      '            if (oldBossLogic != null) oldBossLogic.SetActive(false);', 
      '            Debug.Log("PRODUCTION: Running Experimental Sprint Feature.");', 
      '        }', 
      '        else', 
      '        {', 
      '            if (experimentalBossLogic != null) experimentalBossLogic.SetActive(false);', 
      '            if (oldBossLogic != null) oldBossLogic.SetActive(true);', 
      '        }', 
      '    }', 
      '}' 
    ].join('\n') : moduleNumber === 18 ? [
      'using UnityEngine;',
      'using UnityEngine.Events;',
      'public class LevelGoal : MonoBehaviour',
      '{',
      '    [Header("Requirements")]',
      '    [SerializeField] private int enemiesToDefeat = 3;',
      '    private int currentEnemiesDefeated = 0;',
      '    [Header("Events")]',
      '    public UnityEvent OnLevelComplete;',
      '    public void RegisterEnemyDeath()',
      '    {',
      '        currentEnemiesDefeated++;',
      '        Debug.Log("Progression: " + currentEnemiesDefeated + "/" + enemiesToDefeat + " enemies cleared.");',
      '        if (currentEnemiesDefeated == enemiesToDefeat)',
      '        {',
      '            CompleteLevel();',
      '        }',
      '    }',
      '    private void CompleteLevel()',
      '    {',
      '        Debug.Log("MASTERY ACHIEVED: Level exit unlocked.");',
      '        if (OnLevelComplete != null) OnLevelComplete.Invoke();',
      '    }',
      '}'
    ].join('\n') : moduleNumber === 19 ? [ 
      'using UnityEngine;', 
      'public class ObjectiveManager : MonoBehaviour', 
      '{', 
      '    [SerializeField] private string targetItemID = "GoldenKey";', 
      '    private void CheckObjective(string id){ if (id == targetItemID) Debug.Log("Objective Met: Item Collected."); }', 
      '}' 
    ].join('\n') : moduleNumber === 20 ? [ 
      'using UnityEngine;', 
      'public class CapstoneValidator : MonoBehaviour', 
      '{', 
      '    [Header("Required Global Systems")]', 
      '    [SerializeField] private bool checkGameManager = true;', 
      '    [SerializeField] private bool checkSceneLoader = true;', 
      '    [SerializeField] private bool checkAudioManager = true;', 
      '    private void Start(){ ValidateSystems(); }', 
      '    private void ValidateSystems()', 
      '    {', 
      '        bool allSystemsReady = true;', 
      '        if (checkGameManager){', 
      '            if (WaveManager.Instance == null){ Debug.LogError("CRITICAL: WaveManager missing from scene!"); allSystemsReady = false; }', 
      '        }', 
      '        if (checkSceneLoader){', 
      '            if (SceneLoader.Instance == null){ Debug.LogWarning("WARNING: SceneLoader missing. Scene transitions may fail."); allSystemsReady = false; }', 
      '        }', 
      '        if (checkAudioManager){ Debug.Log("Audio manager check flagged. Validate scene audio bootstrap manually."); }', 
      '        if (allSystemsReady){ Debug.Log("GOLD MASTER VALIDATION: All core systems integrated and ready."); }', 
      '        else{ Debug.LogError("INTEGRATION FAILED: Check console for missing managers."); }', 
      '    }', 
      '}' 
        ].join('\n') : moduleNumber === 21 ? [
      '// Roll-a-Ball: PlayerController', 
      'using UnityEngine;', 
      'public class PlayerController : MonoBehaviour { public float speed = 10f; private Rigidbody rb; private int score; void Start(){ rb = GetComponent(typeof(Rigidbody)) as Rigidbody; } void FixedUpdate(){ rb.AddForce(new Vector3(Input.GetAxis("Horizontal"),0f,Input.GetAxis("Vertical")) * speed); } void OnTriggerEnter(Collider other){ if (other.gameObject.CompareTag("PickUp")){ Destroy(other.gameObject); score++; Debug.Log("Score: " + score); } } }', 
      '', 
      '// Roll-a-Ball: Rotator', 
      'public class Rotator : MonoBehaviour { void Update(){ transform.Rotate(new Vector3(15f,30f,45f) * Time.deltaTime); } }', 
    ].join('\n') : moduleNumber === 22 ? [
      '// Pong: BallController', 
      'using UnityEngine;', 
      'public class BallController : MonoBehaviour { public float initialSpeed = 5f; private Rigidbody2D rb; void Start(){ rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D; LaunchBall(); } public void LaunchBall(){ float x = Random.Range(0,2) == 0 ? -1f : 1f; float y = Random.Range(0,2) == 0 ? -1f : 1f; rb.velocity = new Vector2(x,y).normalized * initialSpeed; } }', 
      '', 
      '// Pong: PaddleController', 
      'public class PaddleController : MonoBehaviour { public float speed = 5f; public string axis = "Vertical"; private Rigidbody2D rb; void Start(){ rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D; } void Update(){ rb.velocity = new Vector2(0f, Input.GetAxis(axis) * speed); } }', 
      '', 
      '// Pong: AIPaddle', 
      'public class AIPaddle : MonoBehaviour { public float speed = 5f; public Transform ball; private Rigidbody2D rb; void Start(){ rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D; } void Update(){ if (ball != null){ float y = Mathf.MoveTowards(transform.position.y, ball.position.y, speed * Time.deltaTime); rb.MovePosition(new Vector2(transform.position.x, y)); } } }', 
    ].join('\n') : moduleNumber === 23 ? [
      '// Space Shooter: PlayerController', 
      'using UnityEngine;', 
      'public class PlayerController : MonoBehaviour { public float speed = 5f; public GameObject laserPrefab; public Transform firePoint; void Update(){ transform.position += new Vector3(Input.GetAxis("Horizontal"), Input.GetAxis("Vertical"), 0f) * speed * Time.deltaTime; if (Input.GetButton("Fire1")){ Instantiate(laserPrefab, firePoint.position, firePoint.rotation); } } }', 
      '', 
      '// Space Shooter: Laser', 
      'public class Laser : MonoBehaviour { public float speed = 10f; void Update(){ transform.Translate(Vector3.up * speed * Time.deltaTime); } void OnTriggerEnter2D(Collider2D other){ if (other.CompareTag("Enemy")){ Destroy(other.gameObject); Destroy(gameObject); } } }', 
      '', 
      '// Space Shooter: SpawnManager', 
      'public class SpawnManager : MonoBehaviour { public GameObject enemyPrefab; public float interval = 1f; private float nextSpawn; void Update(){ if (Time.time == Time.time){ Instantiate(enemyPrefab, new Vector2(Random.Range(-8f,8f), 6f), Quaternion.identity); nextSpawn = Time.time + interval; } } }', 
    ].join('\n') : moduleNumber === 24 ? [
      '// Snake: Head Controller', 
      'using UnityEngine;', 
      'using System.Collections.Generic;', 
      'public class Snake : MonoBehaviour { void Start(){ Debug.Log("Snake start"); } void Update(){ if (Input.GetKeyDown(KeyCode.W)){ transform.Translate(Vector2.up); } } }', 
      '', 
      '// Snake: BodySegment', 
      'public class BodySegment : MonoBehaviour { void Start(){ gameObject.tag = "Body"; } }', 
    ].join('\n') : moduleNumber === 25 ? [
      '// PlayerController',
      'using UnityEngine;',
      'public class PlayerController : MonoBehaviour',
      '{',
      '    public float jumpForce = 10f;',
      '    public float speed = 5f;',
      '    private Rigidbody2D rb;',
      '    private bool isGrounded = true;',
      '    void Start(){ rb = GetComponent(typeof(Rigidbody2D)) as Rigidbody2D; }',
      '    void Update(){ transform.Translate(Vector2.right * speed * Time.deltaTime); if (Input.GetKeyDown(KeyCode.Space)){ if (isGrounded){ rb.velocity = new Vector2(rb.velocity.x, jumpForce); isGrounded = false; } } }',
      '    void OnCollisionEnter2D(Collision2D c){ if (c.gameObject.CompareTag("Ground")){ isGrounded = true; } }',
      '    void OnTriggerEnter2D(Collider2D other){ if (other.CompareTag("Obstacle")){ Time.timeScale = 0f; Debug.Log("Game Over"); } }',
      '}',
      '',
      '// ObstacleSpawner',
      'public class ObstacleSpawner : MonoBehaviour',
      '{',
      '    public GameObject obstaclePrefab;',
      '    public float spawnInterval = 2f;',
      '    public float spawnX = 10f;',
      '    public float minY = 0f;',
      '    public float maxY = 2f;',
      '    private float nextSpawnTime;',
      '    void Update(){ if (Time.time >= nextSpawnTime){ Spawn(); nextSpawnTime = Time.time + spawnInterval; } }',
      '    void Spawn(){ float y = Random.Range(minY, maxY); Instantiate(obstaclePrefab, new Vector2(spawnX, y), Quaternion.identity); }',
      '}',
      '',
      '// ObstacleMover',
      'public class ObstacleMover : MonoBehaviour',
      '{',
      '    public float speed = 5f;',
      '    void Update(){ transform.Translate(Vector2.left * speed * Time.deltaTime); }',
      '}',
      '',
      '// CameraFollow',
      'public class CameraFollow : MonoBehaviour',
      '{',
      '    public Transform player;',
      '    public float offsetX = 2f;',
      '    void LateUpdate(){ if (player != null){ transform.position = new Vector3(player.position.x + offsetX, transform.position.y, transform.position.z); } }',
      '}',
      '',
      '// DistanceScore',
      'public class DistanceScore : MonoBehaviour',
      '{',
      '    public Transform player;',
      '    public UnityEngine.UI.Text scoreText;',
      '    private float startX;',
      '    void Start(){ if (player != null) startX = player.position.x; }',
      '    void Update(){ if (player != null){ if (scoreText != null){ int score = Mathf.Max(0, Mathf.FloorToInt(player.position.x - startX)); scoreText.text = "Score: " + score; } } }',
      '}'
    ].join('\n') : [






      '// Module ' + moduleNumber + ': ' + moduleTitle, 
      '// Stage: ' + stage, 
      '// Focus: ' + focus, 
      'using UnityEngine;', 
      'using UnityEngine.SceneManagement; // Required for scene logic', 
      '', 
      'public class SceneIdentifier : MonoBehaviour', 
      '{', 
      '    void Start()', 
      '    {', 
      '        // Get the name of the scene this script is currently in', 
      '        string currentSceneName = SceneManager.GetActiveScene().name;', 
      '', 
      '        Debug.Log(\"SUCCESS: Module ' + moduleNumber + ' active in scene: \" + currentSceneName);', 
      '', 
      '        // Checklist verification', 
      '        VerifyWorkspace();', 
      '    }', 
      '', 
      '    private void VerifyWorkspace()', 
      '    {', 
      '        Debug.Log(\"Verification: Ensure your Main Camera is set to Orthographic for 2D development.\");', 
      '    }', 
      '}' 
    ].join('\n') 
  }; 
} 
 
function buildPhase(id: number) { 
  const rows = modules.filter(function(m) { return m[0] === id; }); 
  const topics = rows.map(function(m) { return m[2]; }); 
  const lessons = rows.map(function(row) { 
    const globalIndex = modules.findIndex(function(m) { return m[3] === row[3]; }); 
    return buildLesson(row, globalIndex); 
  }); 
  return { id: id, title: phaseTitles[id], topics: topics, lessons: lessons }; 
} 
 
export const gameDevelopmentPhases = [buildPhase(1), buildPhase(2), buildPhase(3), buildPhase(4), buildPhase(5)]; 
export const gameDevelopmentContent = gameDevelopmentPhases[0];
