# Generated by Django 5.0.1 on 2026-02-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium - ₹100/month')], default='free', max_length=20),
        ),
    ]
