# Generated by Django 5.0.1 on 2026-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='test_cases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='validation_code',
            field=models.TextField(blank=True),
        ),
    ]
