# Generated by Django 5.0.1 on 2026-03-06 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_lesson_has_validation_lesson_test_cases_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(choices=[('mern', 'Full Stack Web Development - MERN Stack'), ('python-fullstack', 'Full Stack Web Development - Python'), ('java-fullstack', 'Full Stack Web Development - Java'), ('mean', 'Full Stack Web Development - .Net & Angular'), ('react-native', 'Mobile App Development - React Native'), ('data-analytics', 'Data Analytics'), ('ai-ml', 'Data Science and AI/ML'), ('iot-ai', 'AI/ML Integration with IOT')], max_length=50)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('is_current', models.BooleanField(default=False)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
