# Generated by Django 5.0.9 on 2026-03-10 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_and_domain_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['MENTOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentbatch',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='linked_students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'STUDENT'}, related_name='linked_parents', to=settings.AUTH_USER_MODEL),
        ),
    ]
